<?php
/**
 * Generate VAPID keys for Web Push notifications.
 * Run once: php setup_vapid_keys.php
 * Requires OpenSSL extension.
 */
if (!extension_loaded('openssl')) {
    die("OpenSSL extension is required. Install it and try again.\n");
}

$keyPair = openssl_pkey_new([
    'private_key_bits' => 2048,
    'private_key_type' => OPENSSL_KEYTYPE_EC,
    'curve_name' => 'prime256v1',
]);

if (!$keyPair) {
    die("Failed to generate key pair.\n");
}

$privateKey = '';
openssl_pkey_export($privateKey, $privateKey, $keyPair);

$keyDetails = openssl_pkey_get_details($keyPair);
$publicKey = $keyDetails['ec']['pub_key'] ?? '';

// Convert raw public key to base64url (uncompressed point 0x04 + x + y)
// PHP's openssl doesn't give us the raw bytes directly in a simple way for EC.
// Use a different approach: generate using PHP's sodium or a simpler method.
// For Web Push VAPID we need the raw public key in base64url format.
// The format is: 04 (uncompressed) + 32 bytes X + 32 bytes Y = 65 bytes

$pub = $keyDetails['ec'] ?? null;
if (!$pub) {
    die("EC key details not available.\n");
}

$x = $pub['x'] ?? '';
$y = $pub['y'] ?? '';
if (strlen($x) !== 32 || strlen($y) !== 32) {
    // Pad if needed
    $x = str_pad($x, 32, "\0", STR_PAD_LEFT);
    $y = str_pad($y, 32, "\0", STR_PAD_LEFT);
}
$rawPublic = "\x04" . $x . $y;
$publicBase64 = rtrim(strtr(base64_encode($rawPublic), '+/', '-_'), '=');

// For private key we need PKCS#8 PEM - but Web Push libraries expect raw private key.
// The minishlink/web-push library uses PEM format. Let's output PEM for both.
$privatePem = $privateKey;

// Extract raw private key from PEM for storage (hex)
$privRes = openssl_pkey_get_private($privatePem);
$privDetails = openssl_pkey_get_details($privRes);
$rawPrivate = $privDetails['ec']['d'] ?? '';
if (strlen($rawPrivate) !== 32) {
    $rawPrivate = str_pad($rawPrivate, 32, "\0", STR_PAD_LEFT);
}
$privateBase64 = rtrim(strtr(base64_encode($rawPrivate), '+/', '-_'), '=');

$config = "<?php\n// Auto-generated by setup_vapid_keys.php - do not commit to version control\n";
$config .= "define('PWA_VAPID_PUBLIC', " . var_export($publicBase64, true) . ");\n";
$config .= "define('PWA_VAPID_PRIVATE', " . var_export($privateBase64, true) . ");\n";

$outFile = __DIR__ . '/pwa_config.local.php';
file_put_contents($outFile, $config);
chmod($outFile, 0600);

echo "VAPID keys generated and saved to pwa_config.local.php\n";
echo "Add pwa_config.local.php to .gitignore to keep keys secret.\n";
